/**
 * capitalSnapshot.ts — Pure functions that render the current
 * Capital Plan state as markdown.
 *
 * Two formats:
 *   buildInvestorUpdateMarkdown(): one-pager you'd paste into an
 *     investor update email — round status, committed totals, runway,
 *     biggest risks.
 *   buildFullSnapshotMarkdown(): everything — every round, every
 *     bucket, every investor, every actual. For sharing with a CFO or
 *     a co-founder for review.
 *
 * Both pure → testable, no side effects. The Page wires them to the
 * Copy button via navigator.clipboard.writeText.
 */

import type {
  CapitalPlanData, CapitalRound, CapitalAllocation,
} from "./CapitalPlan.queries";
import {
  summarizeRoundProgress, estimateMonthlyBurn, projectRunwayMonths, totalRaisedToDate,
} from "./CapitalPlan.queries";

interface SnapshotContext {
  plan: CapitalPlanData;
  cashOnHand: number;
}

// ─── Investor-update format (short) ─────────────────────────────

export function buildInvestorUpdateMarkdown({ plan, cashOnHand }: SnapshotContext): string {
  const burn = estimateMonthlyBurn(plan.actuals, plan.allocations);
  const runway = projectRunwayMonths(cashOnHand, burn);
  const raised = totalRaisedToDate(plan.rounds, plan.checks);
  const activeRounds = plan.rounds.filter((r) => r.status === "raising" || r.status === "planning");

  const lines: string[] = [];
  lines.push(`# Capital snapshot — ${new Date().toLocaleDateString(undefined, { month: "long", year: "numeric" })}`);
  lines.push("");
  lines.push(`**Cash on hand:** ${fmt(cashOnHand)}  `);
  lines.push(`**Monthly burn:** ${fmt(burn)}/mo  `);
  lines.push(`**Runway:** ${runway === Infinity ? "n/a (no burn recorded)" : runway.toFixed(1) + " months"}  `);
  lines.push(`**Total raised to date:** ${fmt(raised)}`);
  lines.push("");

  if (activeRounds.length > 0) {
    lines.push("## In-flight rounds");
    lines.push("");
    for (const r of activeRounds) {
      const prog = summarizeRoundProgress(r, plan.checks);
      const daysLeft = prog.daysUntilTargetClose;
      lines.push(`- **${r.name}** — ${prettyType(r.round_type)} · ${r.instrument.toUpperCase()}`);
      lines.push(`  - Target: ${fmt(r.target_amount)}${r.valuation_cap ? ` @ ${fmt(r.valuation_cap)} cap` : ""}`);
      lines.push(`  - Committed: ${fmt(prog.committed)} (${(prog.pctOfTarget * 100).toFixed(0)}%) across ${prog.count} investor${prog.count === 1 ? "" : "s"}`);
      if (daysLeft !== null) {
        lines.push(`  - Target close: ${new Date(r.target_close_date!).toLocaleDateString()} (${daysLeft >= 0 ? `${daysLeft}d to go` : `${Math.abs(daysLeft)}d past`})`);
      }
    }
    lines.push("");
  }

  lines.push(`_Generated by CWA TakeOver Capital Plan — ${new Date().toLocaleString()}_`);
  return lines.join("\n");
}

// ─── Full snapshot format (long) ────────────────────────────────

export function buildFullSnapshotMarkdown({ plan, cashOnHand }: SnapshotContext): string {
  const lines: string[] = [];
  lines.push(buildInvestorUpdateMarkdown({ plan, cashOnHand }));
  lines.push("");
  lines.push("## All rounds");
  lines.push("");
  lines.push("| Round | Type | Status | Target | Cap | Committed | Close target |");
  lines.push("|---|---|---|---:|---:|---:|---|");
  for (const r of plan.rounds) {
    const prog = summarizeRoundProgress(r, plan.checks);
    lines.push(
      `| ${r.name} | ${prettyType(r.round_type)} | ${r.status} | ${fmt(r.target_amount)} | ${r.valuation_cap ? fmt(r.valuation_cap) : "—"} | ${fmt(prog.committed)} (${(prog.pctOfTarget * 100).toFixed(0)}%) | ${r.target_close_date ?? "—"} |`,
    );
  }
  lines.push("");

  if (plan.checks.length > 0) {
    lines.push("## Investor pipeline");
    lines.push("");
    lines.push("| Investor | Round | Status | Check | Last touch | Next step |");
    lines.push("|---|---|---|---:|---|---|");
    for (const c of [...plan.checks].sort((a, b) =>
      (b.priority - a.priority) || a.investor_name.localeCompare(b.investor_name),
    )) {
      const r = plan.rounds.find((x) => x.id === c.round_id);
      lines.push(
        `| ${c.investor_name}${c.firm ? ` (${c.firm})` : ""} | ${r?.name ?? "—"} | ${c.status} | ${fmt(c.check_amount)} | ${c.last_touch_at ? new Date(c.last_touch_at).toLocaleDateString() : "—"} | ${c.next_step ?? "—"} |`,
      );
    }
    lines.push("");
  }

  if (plan.allocations.length > 0) {
    lines.push("## Budget allocation");
    lines.push("");
    const byRound = new Map<string, CapitalAllocation[]>();
    for (const a of plan.allocations) {
      const arr = byRound.get(a.round_id) ?? [];
      arr.push(a);
      byRound.set(a.round_id, arr);
    }
    for (const [roundId, allocs] of byRound.entries()) {
      const r = plan.rounds.find((x) => x.id === roundId);
      if (!r) continue;
      const total = allocs.reduce((s, a) => s + a.planned_amount, 0);
      lines.push(`### ${r.name} — ${fmt(total)} allocated`);
      lines.push("");
      lines.push("| Bucket | Category | Planned | % |");
      lines.push("|---|---|---:|---:|");
      for (const a of allocs.sort((x, y) => y.planned_amount - x.planned_amount)) {
        const pct = total > 0 ? (a.planned_amount / total) * 100 : 0;
        lines.push(`| ${a.bucket_name} | ${a.category} | ${fmt(a.planned_amount)} | ${pct.toFixed(1)}% |`);
      }
      lines.push("");
    }
  }

  if (plan.actuals.length > 0) {
    const totalSpent = plan.actuals.reduce((s, a) => s + a.amount, 0);
    lines.push(`## Recent actuals — ${fmt(totalSpent)} total`);
    lines.push("");
    const recent = [...plan.actuals]
      .sort((a, b) => b.occurred_on.localeCompare(a.occurred_on))
      .slice(0, 25);
    lines.push("| Date | Vendor | Bucket | Amount |");
    lines.push("|---|---|---|---:|");
    for (const a of recent) {
      const alloc = a.allocation_id ? plan.allocations.find((x) => x.id === a.allocation_id) : null;
      lines.push(`| ${a.occurred_on} | ${a.vendor ?? "—"} | ${alloc?.bucket_name ?? "—"} | ${fmt(a.amount)} |`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

// ─── Helpers ────────────────────────────────────────────────────

function fmt(n: number): string {
  if (Math.abs(n) >= 1_000_000) return `$${(n / 1_000_000).toFixed(n % 1_000_000 === 0 ? 0 : 2)}M`;
  if (Math.abs(n) >= 1_000) return `$${(n / 1_000).toFixed(0)}K`;
  return `$${Math.round(n)}`;
}

function prettyType(t: CapitalRound["round_type"]): string {
  const map: Record<CapitalRound["round_type"], string> = {
    "angel": "Angel",
    "pre-seed": "Pre-Seed",
    "seed": "Seed",
    "series-a": "Series A",
    "series-b": "Series B",
    "series-c": "Series C",
    "bridge": "Bridge",
    "extension": "Extension",
  };
  return map[t] ?? t;
}
