/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const TrainingplanLazyRouteImport = createFileRoute('/trainingplan')()
const TimetrackingLazyRouteImport = createFileRoute('/timetracking')()
const TaskLazyRouteImport = createFileRoute('/task')()
const SettingsLazyRouteImport = createFileRoute('/settings')()
const ScheduleLazyRouteImport = createFileRoute('/schedule')()
const SUsersLazyRouteImport = createFileRoute('/s-users')()
const SOverridesLazyRouteImport = createFileRoute('/s-overrides')()
const SFinanceOpsLazyRouteImport = createFileRoute('/s-finance-ops')()
const SDevConsoleLazyRouteImport = createFileRoute('/s-dev-console')()
const SBroadcastLazyRouteImport = createFileRoute('/s-broadcast')()
const SAnalyticsLazyRouteImport = createFileRoute('/s-analytics')()
const RoadmapLazyRouteImport = createFileRoute('/roadmap')()
const QuotaLazyRouteImport = createFileRoute('/quota')()
const PersonalLazyRouteImport = createFileRoute('/personal')()
const OffersLazyRouteImport = createFileRoute('/offers')()
const Mod_logsLazyRouteImport = createFileRoute('/mod_logs')()
const InvoicerLazyRouteImport = createFileRoute('/invoicer')()
const FinancialDashboardLazyRouteImport = createFileRoute(
  '/financialDashboard',
)()
const EmployeeLazyRouteImport = createFileRoute('/employee')()
const DetailsLazyRouteImport = createFileRoute('/details')()
const DetailFoldersLazyRouteImport = createFileRoute('/detailFolders')()
const ContractGeneratorLazyRouteImport = createFileRoute('/contractGenerator')()
const ColdEmailLazyRouteImport = createFileRoute('/coldEmail')()
const ChatLazyRouteImport = createFileRoute('/chat')()
const BudgetaryLazyRouteImport = createFileRoute('/budgetary')()
const BroadcastLazyRouteImport = createFileRoute('/broadcast')()
const BotLazyRouteImport = createFileRoute('/bot')()
const BioLazyRouteImport = createFileRoute('/bio')()
const ArabicLazyRouteImport = createFileRoute('/arabic')()
const AnalyticsLazyRouteImport = createFileRoute('/analytics')()
const IndexLazyRouteImport = createFileRoute('/')()
const ClientIndexLazyRouteImport = createFileRoute('/client/')()
const OfferAcceptTokenLazyRouteImport = createFileRoute(
  '/offer/accept/$token',
)()

const TrainingplanLazyRoute = TrainingplanLazyRouteImport.update({
  id: '/trainingplan',
  path: '/trainingplan',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/trainingplan.lazy').then((d) => d.Route))
const TimetrackingLazyRoute = TimetrackingLazyRouteImport.update({
  id: '/timetracking',
  path: '/timetracking',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/timetracking.lazy').then((d) => d.Route))
const TaskLazyRoute = TaskLazyRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/task.lazy').then((d) => d.Route))
const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const ScheduleLazyRoute = ScheduleLazyRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/schedule.lazy').then((d) => d.Route))
const SUsersLazyRoute = SUsersLazyRouteImport.update({
  id: '/s-users',
  path: '/s-users',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/s-users.lazy').then((d) => d.Route))
const SOverridesLazyRoute = SOverridesLazyRouteImport.update({
  id: '/s-overrides',
  path: '/s-overrides',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/s-overrides.lazy').then((d) => d.Route))
const SFinanceOpsLazyRoute = SFinanceOpsLazyRouteImport.update({
  id: '/s-finance-ops',
  path: '/s-finance-ops',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/s-finance-ops.lazy').then((d) => d.Route))
const SDevConsoleLazyRoute = SDevConsoleLazyRouteImport.update({
  id: '/s-dev-console',
  path: '/s-dev-console',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/s-dev-console.lazy').then((d) => d.Route))
const SBroadcastLazyRoute = SBroadcastLazyRouteImport.update({
  id: '/s-broadcast',
  path: '/s-broadcast',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/s-broadcast.lazy').then((d) => d.Route))
const SAnalyticsLazyRoute = SAnalyticsLazyRouteImport.update({
  id: '/s-analytics',
  path: '/s-analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/s-analytics.lazy').then((d) => d.Route))
const RoadmapLazyRoute = RoadmapLazyRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/roadmap.lazy').then((d) => d.Route))
const QuotaLazyRoute = QuotaLazyRouteImport.update({
  id: '/quota',
  path: '/quota',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/quota.lazy').then((d) => d.Route))
const PersonalLazyRoute = PersonalLazyRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/personal.lazy').then((d) => d.Route))
const OffersLazyRoute = OffersLazyRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/offers.lazy').then((d) => d.Route))
const Mod_logsLazyRoute = Mod_logsLazyRouteImport.update({
  id: '/mod_logs',
  path: '/mod_logs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/mod_logs.lazy').then((d) => d.Route))
const InvoicerLazyRoute = InvoicerLazyRouteImport.update({
  id: '/invoicer',
  path: '/invoicer',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/invoicer.lazy').then((d) => d.Route))
const FinancialDashboardLazyRoute = FinancialDashboardLazyRouteImport.update({
  id: '/financialDashboard',
  path: '/financialDashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/financialDashboard.lazy').then((d) => d.Route),
)
const EmployeeLazyRoute = EmployeeLazyRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/employee.lazy').then((d) => d.Route))
const DetailsLazyRoute = DetailsLazyRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/details.lazy').then((d) => d.Route))
const DetailFoldersLazyRoute = DetailFoldersLazyRouteImport.update({
  id: '/detailFolders',
  path: '/detailFolders',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/detailFolders.lazy').then((d) => d.Route))
const ContractGeneratorLazyRoute = ContractGeneratorLazyRouteImport.update({
  id: '/contractGenerator',
  path: '/contractGenerator',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/contractGenerator.lazy').then((d) => d.Route),
)
const ColdEmailLazyRoute = ColdEmailLazyRouteImport.update({
  id: '/coldEmail',
  path: '/coldEmail',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/coldEmail.lazy').then((d) => d.Route))
const ChatLazyRoute = ChatLazyRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/chat.lazy').then((d) => d.Route))
const BudgetaryLazyRoute = BudgetaryLazyRouteImport.update({
  id: '/budgetary',
  path: '/budgetary',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/budgetary.lazy').then((d) => d.Route))
const BroadcastLazyRoute = BroadcastLazyRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/broadcast.lazy').then((d) => d.Route))
const BotLazyRoute = BotLazyRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/bot.lazy').then((d) => d.Route))
const BioLazyRoute = BioLazyRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/bio.lazy').then((d) => d.Route))
const ArabicLazyRoute = ArabicLazyRouteImport.update({
  id: '/arabic',
  path: '/arabic',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/arabic.lazy').then((d) => d.Route))
const AnalyticsLazyRoute = AnalyticsLazyRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/analytics.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ClientIndexLazyRoute = ClientIndexLazyRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/client/index.lazy').then((d) => d.Route))
const OfferAcceptTokenLazyRoute = OfferAcceptTokenLazyRouteImport.update({
  id: '/offer/accept/$token',
  path: '/offer/accept/$token',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/offer.accept.$token.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/analytics': typeof AnalyticsLazyRoute
  '/arabic': typeof ArabicLazyRoute
  '/bio': typeof BioLazyRoute
  '/bot': typeof BotLazyRoute
  '/broadcast': typeof BroadcastLazyRoute
  '/budgetary': typeof BudgetaryLazyRoute
  '/chat': typeof ChatLazyRoute
  '/coldEmail': typeof ColdEmailLazyRoute
  '/contractGenerator': typeof ContractGeneratorLazyRoute
  '/detailFolders': typeof DetailFoldersLazyRoute
  '/details': typeof DetailsLazyRoute
  '/employee': typeof EmployeeLazyRoute
  '/financialDashboard': typeof FinancialDashboardLazyRoute
  '/invoicer': typeof InvoicerLazyRoute
  '/mod_logs': typeof Mod_logsLazyRoute
  '/offers': typeof OffersLazyRoute
  '/personal': typeof PersonalLazyRoute
  '/quota': typeof QuotaLazyRoute
  '/roadmap': typeof RoadmapLazyRoute
  '/s-analytics': typeof SAnalyticsLazyRoute
  '/s-broadcast': typeof SBroadcastLazyRoute
  '/s-dev-console': typeof SDevConsoleLazyRoute
  '/s-finance-ops': typeof SFinanceOpsLazyRoute
  '/s-overrides': typeof SOverridesLazyRoute
  '/s-users': typeof SUsersLazyRoute
  '/schedule': typeof ScheduleLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/task': typeof TaskLazyRoute
  '/timetracking': typeof TimetrackingLazyRoute
  '/trainingplan': typeof TrainingplanLazyRoute
  '/client/': typeof ClientIndexLazyRoute
  '/offer/accept/$token': typeof OfferAcceptTokenLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/analytics': typeof AnalyticsLazyRoute
  '/arabic': typeof ArabicLazyRoute
  '/bio': typeof BioLazyRoute
  '/bot': typeof BotLazyRoute
  '/broadcast': typeof BroadcastLazyRoute
  '/budgetary': typeof BudgetaryLazyRoute
  '/chat': typeof ChatLazyRoute
  '/coldEmail': typeof ColdEmailLazyRoute
  '/contractGenerator': typeof ContractGeneratorLazyRoute
  '/detailFolders': typeof DetailFoldersLazyRoute
  '/details': typeof DetailsLazyRoute
  '/employee': typeof EmployeeLazyRoute
  '/financialDashboard': typeof FinancialDashboardLazyRoute
  '/invoicer': typeof InvoicerLazyRoute
  '/mod_logs': typeof Mod_logsLazyRoute
  '/offers': typeof OffersLazyRoute
  '/personal': typeof PersonalLazyRoute
  '/quota': typeof QuotaLazyRoute
  '/roadmap': typeof RoadmapLazyRoute
  '/s-analytics': typeof SAnalyticsLazyRoute
  '/s-broadcast': typeof SBroadcastLazyRoute
  '/s-dev-console': typeof SDevConsoleLazyRoute
  '/s-finance-ops': typeof SFinanceOpsLazyRoute
  '/s-overrides': typeof SOverridesLazyRoute
  '/s-users': typeof SUsersLazyRoute
  '/schedule': typeof ScheduleLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/task': typeof TaskLazyRoute
  '/timetracking': typeof TimetrackingLazyRoute
  '/trainingplan': typeof TrainingplanLazyRoute
  '/client': typeof ClientIndexLazyRoute
  '/offer/accept/$token': typeof OfferAcceptTokenLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/analytics': typeof AnalyticsLazyRoute
  '/arabic': typeof ArabicLazyRoute
  '/bio': typeof BioLazyRoute
  '/bot': typeof BotLazyRoute
  '/broadcast': typeof BroadcastLazyRoute
  '/budgetary': typeof BudgetaryLazyRoute
  '/chat': typeof ChatLazyRoute
  '/coldEmail': typeof ColdEmailLazyRoute
  '/contractGenerator': typeof ContractGeneratorLazyRoute
  '/detailFolders': typeof DetailFoldersLazyRoute
  '/details': typeof DetailsLazyRoute
  '/employee': typeof EmployeeLazyRoute
  '/financialDashboard': typeof FinancialDashboardLazyRoute
  '/invoicer': typeof InvoicerLazyRoute
  '/mod_logs': typeof Mod_logsLazyRoute
  '/offers': typeof OffersLazyRoute
  '/personal': typeof PersonalLazyRoute
  '/quota': typeof QuotaLazyRoute
  '/roadmap': typeof RoadmapLazyRoute
  '/s-analytics': typeof SAnalyticsLazyRoute
  '/s-broadcast': typeof SBroadcastLazyRoute
  '/s-dev-console': typeof SDevConsoleLazyRoute
  '/s-finance-ops': typeof SFinanceOpsLazyRoute
  '/s-overrides': typeof SOverridesLazyRoute
  '/s-users': typeof SUsersLazyRoute
  '/schedule': typeof ScheduleLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/task': typeof TaskLazyRoute
  '/timetracking': typeof TimetrackingLazyRoute
  '/trainingplan': typeof TrainingplanLazyRoute
  '/client/': typeof ClientIndexLazyRoute
  '/offer/accept/$token': typeof OfferAcceptTokenLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/arabic'
    | '/bio'
    | '/bot'
    | '/broadcast'
    | '/budgetary'
    | '/chat'
    | '/coldEmail'
    | '/contractGenerator'
    | '/detailFolders'
    | '/details'
    | '/employee'
    | '/financialDashboard'
    | '/invoicer'
    | '/mod_logs'
    | '/offers'
    | '/personal'
    | '/quota'
    | '/roadmap'
    | '/s-analytics'
    | '/s-broadcast'
    | '/s-dev-console'
    | '/s-finance-ops'
    | '/s-overrides'
    | '/s-users'
    | '/schedule'
    | '/settings'
    | '/task'
    | '/timetracking'
    | '/trainingplan'
    | '/client/'
    | '/offer/accept/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/arabic'
    | '/bio'
    | '/bot'
    | '/broadcast'
    | '/budgetary'
    | '/chat'
    | '/coldEmail'
    | '/contractGenerator'
    | '/detailFolders'
    | '/details'
    | '/employee'
    | '/financialDashboard'
    | '/invoicer'
    | '/mod_logs'
    | '/offers'
    | '/personal'
    | '/quota'
    | '/roadmap'
    | '/s-analytics'
    | '/s-broadcast'
    | '/s-dev-console'
    | '/s-finance-ops'
    | '/s-overrides'
    | '/s-users'
    | '/schedule'
    | '/settings'
    | '/task'
    | '/timetracking'
    | '/trainingplan'
    | '/client'
    | '/offer/accept/$token'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/arabic'
    | '/bio'
    | '/bot'
    | '/broadcast'
    | '/budgetary'
    | '/chat'
    | '/coldEmail'
    | '/contractGenerator'
    | '/detailFolders'
    | '/details'
    | '/employee'
    | '/financialDashboard'
    | '/invoicer'
    | '/mod_logs'
    | '/offers'
    | '/personal'
    | '/quota'
    | '/roadmap'
    | '/s-analytics'
    | '/s-broadcast'
    | '/s-dev-console'
    | '/s-finance-ops'
    | '/s-overrides'
    | '/s-users'
    | '/schedule'
    | '/settings'
    | '/task'
    | '/timetracking'
    | '/trainingplan'
    | '/client/'
    | '/offer/accept/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AnalyticsLazyRoute: typeof AnalyticsLazyRoute
  ArabicLazyRoute: typeof ArabicLazyRoute
  BioLazyRoute: typeof BioLazyRoute
  BotLazyRoute: typeof BotLazyRoute
  BroadcastLazyRoute: typeof BroadcastLazyRoute
  BudgetaryLazyRoute: typeof BudgetaryLazyRoute
  ChatLazyRoute: typeof ChatLazyRoute
  ColdEmailLazyRoute: typeof ColdEmailLazyRoute
  ContractGeneratorLazyRoute: typeof ContractGeneratorLazyRoute
  DetailFoldersLazyRoute: typeof DetailFoldersLazyRoute
  DetailsLazyRoute: typeof DetailsLazyRoute
  EmployeeLazyRoute: typeof EmployeeLazyRoute
  FinancialDashboardLazyRoute: typeof FinancialDashboardLazyRoute
  InvoicerLazyRoute: typeof InvoicerLazyRoute
  Mod_logsLazyRoute: typeof Mod_logsLazyRoute
  OffersLazyRoute: typeof OffersLazyRoute
  PersonalLazyRoute: typeof PersonalLazyRoute
  QuotaLazyRoute: typeof QuotaLazyRoute
  RoadmapLazyRoute: typeof RoadmapLazyRoute
  SAnalyticsLazyRoute: typeof SAnalyticsLazyRoute
  SBroadcastLazyRoute: typeof SBroadcastLazyRoute
  SDevConsoleLazyRoute: typeof SDevConsoleLazyRoute
  SFinanceOpsLazyRoute: typeof SFinanceOpsLazyRoute
  SOverridesLazyRoute: typeof SOverridesLazyRoute
  SUsersLazyRoute: typeof SUsersLazyRoute
  ScheduleLazyRoute: typeof ScheduleLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  TaskLazyRoute: typeof TaskLazyRoute
  TimetrackingLazyRoute: typeof TimetrackingLazyRoute
  TrainingplanLazyRoute: typeof TrainingplanLazyRoute
  ClientIndexLazyRoute: typeof ClientIndexLazyRoute
  OfferAcceptTokenLazyRoute: typeof OfferAcceptTokenLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainingplan': {
      id: '/trainingplan'
      path: '/trainingplan'
      fullPath: '/trainingplan'
      preLoaderRoute: typeof TrainingplanLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetracking': {
      id: '/timetracking'
      path: '/timetracking'
      fullPath: '/timetracking'
      preLoaderRoute: typeof TimetrackingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task': {
      id: '/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof TaskLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s-users': {
      id: '/s-users'
      path: '/s-users'
      fullPath: '/s-users'
      preLoaderRoute: typeof SUsersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s-overrides': {
      id: '/s-overrides'
      path: '/s-overrides'
      fullPath: '/s-overrides'
      preLoaderRoute: typeof SOverridesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s-finance-ops': {
      id: '/s-finance-ops'
      path: '/s-finance-ops'
      fullPath: '/s-finance-ops'
      preLoaderRoute: typeof SFinanceOpsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s-dev-console': {
      id: '/s-dev-console'
      path: '/s-dev-console'
      fullPath: '/s-dev-console'
      preLoaderRoute: typeof SDevConsoleLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s-broadcast': {
      id: '/s-broadcast'
      path: '/s-broadcast'
      fullPath: '/s-broadcast'
      preLoaderRoute: typeof SBroadcastLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s-analytics': {
      id: '/s-analytics'
      path: '/s-analytics'
      fullPath: '/s-analytics'
      preLoaderRoute: typeof SAnalyticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quota': {
      id: '/quota'
      path: '/quota'
      fullPath: '/quota'
      preLoaderRoute: typeof QuotaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod_logs': {
      id: '/mod_logs'
      path: '/mod_logs'
      fullPath: '/mod_logs'
      preLoaderRoute: typeof Mod_logsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoicer': {
      id: '/invoicer'
      path: '/invoicer'
      fullPath: '/invoicer'
      preLoaderRoute: typeof InvoicerLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financialDashboard': {
      id: '/financialDashboard'
      path: '/financialDashboard'
      fullPath: '/financialDashboard'
      preLoaderRoute: typeof FinancialDashboardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detailFolders': {
      id: '/detailFolders'
      path: '/detailFolders'
      fullPath: '/detailFolders'
      preLoaderRoute: typeof DetailFoldersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractGenerator': {
      id: '/contractGenerator'
      path: '/contractGenerator'
      fullPath: '/contractGenerator'
      preLoaderRoute: typeof ContractGeneratorLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coldEmail': {
      id: '/coldEmail'
      path: '/coldEmail'
      fullPath: '/coldEmail'
      preLoaderRoute: typeof ColdEmailLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgetary': {
      id: '/budgetary'
      path: '/budgetary'
      fullPath: '/budgetary'
      preLoaderRoute: typeof BudgetaryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast': {
      id: '/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof BroadcastLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot': {
      id: '/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof BotLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bio': {
      id: '/bio'
      path: '/bio'
      fullPath: '/bio'
      preLoaderRoute: typeof BioLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arabic': {
      id: '/arabic'
      path: '/arabic'
      fullPath: '/arabic'
      preLoaderRoute: typeof ArabicLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/accept/$token': {
      id: '/offer/accept/$token'
      path: '/offer/accept/$token'
      fullPath: '/offer/accept/$token'
      preLoaderRoute: typeof OfferAcceptTokenLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AnalyticsLazyRoute: AnalyticsLazyRoute,
  ArabicLazyRoute: ArabicLazyRoute,
  BioLazyRoute: BioLazyRoute,
  BotLazyRoute: BotLazyRoute,
  BroadcastLazyRoute: BroadcastLazyRoute,
  BudgetaryLazyRoute: BudgetaryLazyRoute,
  ChatLazyRoute: ChatLazyRoute,
  ColdEmailLazyRoute: ColdEmailLazyRoute,
  ContractGeneratorLazyRoute: ContractGeneratorLazyRoute,
  DetailFoldersLazyRoute: DetailFoldersLazyRoute,
  DetailsLazyRoute: DetailsLazyRoute,
  EmployeeLazyRoute: EmployeeLazyRoute,
  FinancialDashboardLazyRoute: FinancialDashboardLazyRoute,
  InvoicerLazyRoute: InvoicerLazyRoute,
  Mod_logsLazyRoute: Mod_logsLazyRoute,
  OffersLazyRoute: OffersLazyRoute,
  PersonalLazyRoute: PersonalLazyRoute,
  QuotaLazyRoute: QuotaLazyRoute,
  RoadmapLazyRoute: RoadmapLazyRoute,
  SAnalyticsLazyRoute: SAnalyticsLazyRoute,
  SBroadcastLazyRoute: SBroadcastLazyRoute,
  SDevConsoleLazyRoute: SDevConsoleLazyRoute,
  SFinanceOpsLazyRoute: SFinanceOpsLazyRoute,
  SOverridesLazyRoute: SOverridesLazyRoute,
  SUsersLazyRoute: SUsersLazyRoute,
  ScheduleLazyRoute: ScheduleLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  TaskLazyRoute: TaskLazyRoute,
  TimetrackingLazyRoute: TimetrackingLazyRoute,
  TrainingplanLazyRoute: TrainingplanLazyRoute,
  ClientIndexLazyRoute: ClientIndexLazyRoute,
  OfferAcceptTokenLazyRoute: OfferAcceptTokenLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
