// Register all AXON actions. Called once from the provider mount.

import { registerNavigationActions } from "./navigation";
import { registerCompanyActions } from "./company";
import { registerTaskActions } from "./tasks";
import { registerDataActions } from "./data";
import { registerBriefingActions } from "./briefing";
import { registerAnnouncementActions } from "./announcements";
import { registerAutomationActions } from "./automations";
import { registerMeetingActions } from "./meetings";
import { registerDomActions } from "./dom";
import { registerRoutineActions } from "./routines";
import { registerMemoryActions } from "./memory";
import { registerTrustActions } from "./trust";
import { registerChatActions } from "./chat";
import { registerUndoActions } from "./undo";
import { registerCeoPowerActions } from "./ceo_powers";
import { registerCwaRegistryActions } from "./cwa_registry";
import { registerHelpActions } from "./help";
import { registerCallActions } from "./call";
import { registerCredentialActions } from "./credentials";
import { registerOutboundActions } from "./outbound";
import { registerIngestActions } from "./ingest";
import { registerWorkflowActions } from "./workflows";
import { registerJournalActions } from "./journal";
import { registerVoiceAuthActions } from "./voiceauth";
import { registerVoiceActions } from "./voice";
import { registerCodeActions } from "./code";
import { registerProjectActions } from "./projects";
import { registerAgentActions } from "./agent";
import { registerEnsembleActions } from "./ensemble";
import { registerRecruitingActions } from "./recruiting";
import { registerOnboardingActions } from "./onboarding";
import { registerSleepActions } from "./sleep";
import { registerThemeActions } from "./theme";
import { registerShiftActions } from "./shifts";
import { registerWorkspaceActions } from "./workspace";
import { registerCapitalPlanActions } from "./capital_plan";
import { registerConnectorActions } from "./connectors";
import { registerCrmActions } from "./crm";

let registered = false;

export function registerAllActions() {
  if (registered) return;
  registered = true;
  registerNavigationActions();
  registerCompanyActions();
  registerTaskActions();
  registerDataActions();
  registerBriefingActions();
  registerAnnouncementActions();
  registerAutomationActions();
  registerMeetingActions();
  registerDomActions();
  registerRoutineActions();
  registerMemoryActions();
  registerTrustActions();
  registerChatActions();
  registerUndoActions();
  registerCeoPowerActions();
  registerCwaRegistryActions();
  registerHelpActions();
  registerCallActions();
  registerCredentialActions();
  registerOutboundActions();
  registerIngestActions();
  registerWorkflowActions();
  registerJournalActions();
  registerVoiceAuthActions();
  registerVoiceActions();
  registerCodeActions();
  registerProjectActions();
  registerAgentActions();
  registerEnsembleActions();
  registerRecruitingActions();
  registerOnboardingActions();
  registerSleepActions();
  registerThemeActions();
  registerShiftActions();
  registerWorkspaceActions();
  registerCapitalPlanActions();
  registerConnectorActions();
  registerCrmActions();
}
